name: Deploy
# on: [push, workflow_dispatch]
on:
    push:
        branches:
            - main
        paths:                 # you can specify which file change will trigger the workflow
            - "src/**"
            - "package.json"
            - "package-lock.json"
            - "index.html"
            - "main.html"
        # paths-ignore:         # you can specify which file change will NOT trigger the workflow
        #     - "README.md"
        #     - ".github/workflows/**"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Clone Repo"
              uses: actions/checkout@v4
            #   run: |                           This is hard way to clone the repo
            #     echo "Cloning repository..."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/ashishDevv/${{github.repository}}.git

            - name: "Install Node.js"
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: "Print Node.js Version"
              run: node -v
            
            - name: "Install Dependencies"
              run: npm ci
            
            - name: "Run Tests"
              run: npm run test
    
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: "Clone Repo"
              uses: actions/checkout@v4
            
            - name: "Install Node.js"
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: "Print Node.js Version"
              run: node -v
            
            - name: "Install Dependencies"
              run: npm ci
            
            - name: "Build Project"
              run: npm run build
            
            - name: "Uploading Build Artifacts"
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: "Download Build Artifacts"
              uses: actions/download-artifact@v4
              with:
                name: dist-files
                path: dist
            - name: "Deploy to Server"
              run: echo "Deploying to server..."
