name: Deploy
on: [push, workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Clone Repo"
              uses: actions/checkout@v4
            #   run: |                           This is hard way to clone the repo
            #     echo "Cloning repository..."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/ashishDevv/${{github.repository}}.git

            - name: "Install Node.js"
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: "Print Node.js Version"
              run: node -v
            
            - name: "Install Dependencies"
              run: npm ci
            
            - name: "Run Tests"
              run: npm run test